package gitutil

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Init initializes a git repo in the given directory.
func Init(dir string) error {
	return run(dir, "git", "init")
}

// CommitAll stages and commits all changes with the given message.
// If there is nothing to commit the call is a no-op.
func CommitAll(dir, message string) error {
	if err := run(dir, "git", "add", "-A"); err != nil {
		return err
	}
	out, err := output(dir, "git", "status", "--porcelain")
	if err != nil {
		return err
	}
	if strings.TrimSpace(out) == "" {
		return nil
	}
	return run(dir, "git", "commit", "-m", message)
}

// Log returns the git log (one-line format) for the directory.
func Log(dir string, maxCount int) (string, error) {
	return output(dir, "git", "log", "--oneline", fmt.Sprintf("-%d", maxCount))
}

// DiffStat returns a diffstat for the last commit.
func DiffStat(dir string) (string, error) {
	return output(dir, "git", "diff", "--stat", "HEAD~1..HEAD")
}

// GeneratePRTemplate creates a PR template markdown file from the git history.
func GeneratePRTemplate(dir, prompt, writerModel, auditorModel string) (string, error) {
	log, _ := Log(dir, 50)

	var sb strings.Builder
	sb.WriteString("## Summary\n\n")
	sb.WriteString("Generated by forge with:\n")
	sb.WriteString(fmt.Sprintf("- **Writer**: %s\n", writerModel))
	sb.WriteString(fmt.Sprintf("- **Auditor**: %s\n\n", auditorModel))
	sb.WriteString("### Prompt\n\n")
	sb.WriteString("> " + strings.ReplaceAll(prompt, "\n", "\n> ") + "\n\n")

	if log != "" {
		sb.WriteString("### Session Rounds\n\n")
		sb.WriteString("```\n" + log + "\n```\n\n")
	}

	sb.WriteString("## Test Plan\n\n")
	sb.WriteString("- [ ] Review generated code\n")
	sb.WriteString("- [ ] Run test suite\n")
	sb.WriteString("- [ ] Verify security hardening\n")
	sb.WriteString("- [ ] Check production readiness\n")

	template := sb.String()

	path := filepath.Join(dir, "PR_TEMPLATE.md")
	if err := os.WriteFile(path, []byte(template), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func run(dir string, name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Stdout = os.Stderr
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func output(dir string, name string, args ...string) (string, error) {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	return string(out), err
}
